hyq2max:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


# Joints Position Controllers ---------------------------------------
  #Left Front Leg ------------
  lf_haa_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lf_haa_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  lf_hfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lf_hfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  lf_kfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lf_kfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}


  #Left Hind Leg ---------------
  lh_haa_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lh_haa_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  lh_hfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lh_hfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  lh_kfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lh_kfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}


#Right Hind Leg ---------------
  rh_haa_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rh_haa_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  rh_hfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rh_hfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  rh_kfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rh_kfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}


#Right Front Leg ---------------
  rf_haa_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rf_haa_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  rf_hfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rf_hfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}

  rf_kfe_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rf_kfe_joint
    pid: {p: 600.0, i: 0.00, d: 10.0}